### PR TITLE
Fix `EventDispatcher` off error

### LINKED ISSUE #1309: `EventDispatcher` dispatch bug when call `off` in  call back.
image

If developer  write `off` in call back, maybe crash

### PR DESCRIPTION
**Pull request by gz65555**
Fix #1309

### CODE REVIEW

File: packages/core/src/base/EventDispatcher.ts [hunk 1]
```diff
@@ -54,14 +55,26 @@ export class EventDispatcher {
...
 
     if (listeners.fn) {
-      if (listeners.once) this.removeEventListener(event, listeners.fn);
+      if (listeners.once) this.off(event, listeners.fn);
       listeners.fn(data);
     } else {
       const l = listeners.length;
+
+      // cloning list to avoid structure breaking
+      const _dispatchingListeners = this._dispatchingListeners;
```
Comment (GuoLei1990) [inline packages/core/src/base/EventDispatcher.ts:64]: use `dispatchingListeners ` instead `_dispatchingListeners `

File: packages/core/src/base/EventDispatcher.ts [hunk 2]
```diff
@@ -54,14 +55,26 @@ export class EventDispatcher {
...
+        _dispatchingListeners[i] = listeners[i];
+      }
+
       for (let i = 0; i < l; i++) {
-        if (listeners[i].once) this.removeEventListener(event, listeners[i].fn);
-        listeners[i].fn(data);
+        if (!_dispatchingListeners[i].destroyed) {
+          if (_dispatchingListeners[i].once) this.off(event, _dispatchingListeners[i].fn);
+          _dispatchingListeners[i].fn(data);
+        }
```
Comment (GuoLei1990) [inline packages/core/src/base/EventDispatcher.ts:73]: Cache element named listener? 
```ts
for (let i = 0; i < l; i++) {
        const listener = dispatchingListeners[i];
        if (!listener.destroyed) {
          if (listener.once) this.off(event, listener.fn);
          listener.fn(data);
        }
      }
```

File: packages/core/src/base/EventDispatcher.ts [hunk 3]
```diff
@@ -8,6 +8,7 @@ export class EventDispatcher {
   @ignoreClone
   private _evts = Object.create(null);
   private _evtCount = 0;
+  private _dispatchingListeners = [];
```
Comment (GuoLei1990) [inline packages/core/src/base/EventDispatcher.ts:11]: Write type and define a interfacte type for listener?

**Review by heyzxz — APPROVED** [review]
